### ISSUE TITLE
composer create-project

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-kickstarter-bootstrap4#1]
Gefällt mir. Ich muss es sicherlich noch umbauen da wir von einem private repo kein "create-project" command ausführen können. Muss ich also noch evaluieren.

http://stackoverflow.com/questions/18160115/composer-create-project-from-private-repo

**Comment by TheMaaarc** [comment]
Ich denke mit diesem Projekt habe wir eine solide Grundlage auf der wir aufbauen können. Jetzt müssen nur noch alle Blöcke auf Bootstrap 4 umgeschrieben werden. :+1:

**Comment by nadar** [comment]
Ich denke wir machen ein "luya-blocks-bootstrap4" repo welches wir einbinden können. Bei den luya basis blocks entfernen wir dafür alle bootstrap spezifsichen syntaxe.
