### ISSUE TITLE
Main.css and Main.min.js not found

### ISSUE THREAD

**Issue by davidtim** [luyadev/luya-kickstarter-bootstrap4#10]
I tried to install and run gulp already but still main.css and main.min.js are not found

**Comment by nadar** [comment]
Hi @davidtim, the gulp workflow is outdated but maybe @TheMaaarc still knows some tricks regarding this. What did you run? Does the workflow create a dist folder with files? 

Maybe take a look at this https://github.com/zephir/luya-unglue-kickstarter

**Comment by davidtim** [comment]
I just run gulp, but I didn’t see it creat any files. I think that’s why,
the Frontenac show errors missing main.css and main.min.js

**Comment by nadar** [comment]
Yes, i think so. Therefore ensure the gulp workflow runs correctly or use https://www.unglue.io/

**Comment by davidtim** [comment]
thank you, i'll try it now

**Comment by davidtim** [comment]
I'm already install unglue.
However, I figured it how on Gulp. The file gulp-config.js has wrong destination path for both css and js
