### ISSUE TITLE
Basic blocks are missing in CMS

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya-kickstarter-bootstrap4#12]
The [BS3 kickstarter](https://github.com/luyadev/luya-kickstarter) installs the module [luya-generic](https://github.com/luyadev/luya-generic) which brings **elementary** blocks for the CMS such as heading, list, text, texteditor etc. This module is missing in the BS4 kickstarter.
It is not expedient to have a complex BS4-Carousel but no basic text block.

Are there any known incompatibilities between `luya-generic` and BS4?
Can we simply add 

```
"require": {
   ...,
   "luyadev/luya-generic" : "^1.0"
},
```
to `composer.json`?

**Comment by nadar** [comment]
Sure 👍 would you like to send a PR? I need to adjust version constraints anyhow

**Comment by hbugdoll** [comment]
Tested in CMS, no obvious problems 😃 

PR is coming...
