### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya-kickstarter-bootstrap4#14]
License is missing... maybe MIT License like the LUYA main modules.

All LUYA modules should have a `LICENSE.md`.

**Comment by nadar** [comment]
yes we should add this everywhere. maybe there is an option to define those informations global with `.github` repo => https://github.com/luyadev/.github

**Comment by nadar** [comment]
> You cannot create a default license file. License files must be added to individual repositories so the file will be included when a project is cloned, packaged, or downloaded.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

 so we have to copy the file from https://github.com/luyadev/luya/blob/master/LICENSE.md to every repo :-)

**Comment by hbugdoll** [comment]
> > You cannot create a default license file. License files must be added to individual repositories so the file will be included when a project is cloned, packaged, or downloaded.

What a pity.
