### ISSUE TITLE
Update docker-compose.yml?

### ISSUE THREAD

**Issue by andrewpros** [luyadev/luya-kickstarter-bootstrap4#20]
U should update the docker-compose.yml to at least latest php 7.4 and maybe add 8.x+ option to choose from.

The current template is only 7.2.29 and this creates issues with development as most packages are transitioning to 8.x or stay (for now) at the latest 7.4.x or provide it for compatibility, but 7.2 is basically outdated.

Also im not sure which docker-compose.yml file structure is now the latest as basic kickstarter does not have the luya_php entry any more, seem like merged with nginx but its 7.4, while this is with luya_php but only 7.2.29, so is there a simple way to update it to 7.4?

**Comment by nadar** [comment]
Yes you are right. There are also already docker images, see this kickstarter f.e => https://github.com/zephir/luya-unglue-kickstarter/blob/master/docker-compose.yml

**Comment by nadar** [comment]
Yes, the above mentioned package combines php with nginx into a single dockerfile, thats right

**Comment by andrewpros** [comment]
Well ok then, the unglue one looks like the basic kickstarter with the merged luya_web, so i assume its the way to go now.
