### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mr-Coquin** [luyadev/luya-kickstarter-bootstrap4#29]
I did the installation using Composer. Did the import and migration. But bootsrap4 didn't show up in the page edit. What needs to be registered perhaps in a config?

**Comment by nadar** [comment]
What do you mean by "showup"? This kickstarter will setup a project, and adding bootstrap 4 blocks from here https://github.com/luyadev/luya-bootstrap4

**Comment by Mr-Coquin** [comment]
I dowlads https://github.com/luyadev/luya-kickstarter-bootstrap4

**Comment by nadar** [comment]
please answer the question, otherwise i can not help and will not spend anymore time here unless you put effort in describe exactly whats your problem including screenshots.

**Comment by Mr-Coquin** [comment]
I'm sorry. I installed another module that I found here. Here is his link:
https://github.com/luyadev/luya-kickstarter-bootstrap4

Nothing appeared in the page edit menu.

But it appeared in another place only in disk space

![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/d6da48c7-ae0a-4599-a6a3-43443cb62436)

**Comment by nadar** [comment]
this is not a module, its a scafolding project, not a module. you can not copy files into another application, this will not do anything. maybe you should try wordpress, there you can do things like that.

**Comment by Mr-Coquin** [comment]
I didn't copy anything. This appeared after the actions described in that instruction

**Comment by nadar** [comment]
Maybe take a look at the difference between `composer require` and `composer create-project`. This a complet different functionality. Require adds librarys (modules), while create project creates you new fresh project. Maybe take a look at this link i shared already once:

https://luya.io/packages.html

There are Kickstarters (create-project commands, to starte a new projects) and modules/extensions (use them with require).

**Comment by Mr-Coquin** [comment]
Yes you are right. Thank you. Say I created my own topic. And I have information loaded there at the end of endBody. But I hang that in the topic I did not add it. I have already read the entire project and documentation. But I can’t understand where this comes from. Javascript is substituted there.

Error
![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/1b2a1c83-2a67-4a8d-9699-1978c84583fc)
![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/a1e85eb3-3bba-47ba-973d-f693e4de37c3)
![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/9e4fe733-1592-41d9-8efd-301bdf5d60ce)
![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/21523513-130c-4fe9-b389-bb4091c816e8)

**Comment by Mr-Coquin** [comment]
Looks like a debug.But in the config file, I disabled it a long time ago. But somewhere it still works as I understand

**Comment by Mr-Coquin** [comment]
Good afternoon. I created my module. based on the address book. And I wanted to add my page. But here I ran into a problem. Need a controller. Tell as it is possible to specify that the controller which works with tables of the general type would undertake.

![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/e9b86994-eea9-4586-a601-dfd37c7a87b7)
![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/7b91f736-e2c2-4a6b-b3e8-63ee1a46aec6)
![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/c447ae16-e5f6-4e77-881d-22a833bfa7a8)

**Comment by Mr-Coquin** [comment]
I also ran into 1 problem. When I create my block. And there I put
  public $cacheEnabled = false;
That at not authorized user there is an error.
![image](https://github.com/luyadev/luya-kickstarter-bootstrap4/assets/123034940/23bab2e6-5ce4-4158-8af1-a5efca958faa)
Worth returning
  public $cacheEnabled = false;
how everything works

**Comment by nadar** [comment]
When you develop, enable yii_debug otherwise you can not see the full stack trace and we can not help.

**Comment by Mr-Coquin** [comment]
Fine. And what about the module. To display its data according to the template

**Comment by nadar** [comment]
sorry, i don't understand that question. (could not see a question).
