### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by siripravi** [luyadev/luya-kickstarter-bootstrap4#32]
### What steps will reproduce the problem?
while running composer install, got an error

### What is the expected result?
luya-kickstarter-bootstrap4 to be installed using composer

### What do you get instead? (A Screenshot can help us a lot!)
` 48/48 [============================] 100%
In ZipDownloader.php line 220:

  'C:\luya-kickstarter-bootstrap4/vendor/composer/tmp-165a360462429839125e3007ea9d6425' is not a zip archive.`

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
i think thats a problem with your local composer/php environment and has nothing todo with luya itself.

**Comment by siripravi** [comment]
Ok.
