### ISSUE TITLE
Bootstrap 4 files from vendor.

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-kickstarter-bootstrap4#5]
It think we should retrieve the bs4 files from vendor instead of copy those files into rsc folders. (like we did in LUYA Admin UI)

**Comment by TheMaaarc** [comment]
I think we already did that and just never closed the issue?

https://github.com/luyadev/luya-kickstarter-bootstrap4/blob/master/resources/scss/main.scss#L13
