### ISSUE TITLE
Can't use yii2 user inferface extensions 

### ISSUE THREAD

**Issue by vavepl** [luyadev/luya-kickstarter-bootstrap4#6]
Hello, I want to use dektrium/yii2-user package, but i have problem with installing it

console log
![image](https://user-images.githubusercontent.com/7990096/38470793-4237fc38-3b68-11e8-9e5a-4253a96470a9.png)

composer.json
![image](https://user-images.githubusercontent.com/7990096/38470802-58d54216-3b68-11e8-9e41-43f832c15f34.png)

**Comment by nadar** [comment]
@vavepl using this composer.json and run composer update works perfect:

```json
    "require": {
        "luyadev/luya-core" : "~1.0.0",
        "luyadev/luya-module-admin" : "~1.1.0",
        "luyadev/luya-module-cms" : "~1.0.0",
        "luyadev/luya-bootstrap4": "^1.0@dev",
        "dektrium/yii2-user" : "~0.9.13"
    },
    "require-dev": {
        "yiisoft/yii2-debug" : "~2.0.0",
        "yiisoft/yii2-gii" : "~2.0.0",
        "luyadev/luya-deployer": "~1.0.0",
        "twbs/bootstrap": "~4.0.0"
    },
```

**Comment by vavepl** [comment]
i use new project template on dev-master. It works! Thanks :)
